name: Test project
 
on:
  workflow_dispatch:
  push:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Project
        uses: actions/checkout@v4
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test