apiVersion: v1
kind: Service
metadata: # metadata about the service
  name: rms-service
spec: # defines the desired state of the Service
  selector:
    app: rms-docker-img
  ports: 
    - protocol: TCP 
      port: 80
      targetPort: 5050
  type: LoadBalancer # expose externally using a public IP  